<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    
    	$product = $objectManager->create(\Magento\Catalog\Model\Product::class);
    /*   $prod_name = $product->getData('name');
      
       echo $prod_name . '<br>';
*/
      $prod_id= $product->getID();
       $productRegistry = $objectManager->get(\Magento\Framework\Registry::class)->registry('current_product');
       echo $productRegistry->getName();
       $prod_var=$product->load($prod_id);
       echo $prod_var->getName();
       echo"fine test";

    /*
     foreach ($_products as $product){
     $prod_name = $product->getData('name');
     echo $prod_name . '<br>';
     $attribute = $product->getData('attribute');
     */
?>