<?php
/**
 * Instagram Widget block template
 *
 * @var $block \Its\NewsletterPopup\Block\NewsletterPopup
 */
?>
<div style="display: none">
    <div class="popup-newsletter">
        <div class="content">
            <!--            <p>--><?php //echo $block->getPopupText();?><!--</p>-->
            <?= $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId($block->getPopupBlockid())
                ->toHtml(); ?>
            <?php echo $block->getChildHtml('newsletter-form'); ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".popup-newsletter": {
            "newsletterPopup": <?php echo \Zend_Json::encode($block->getConfig()) ?>
        }
    }




</script>


